"""Platform-side primitives shared by every tool handler.

This module is the difference between "yet another MCP server" and a platform.
Adapters should never reimplement these:

    Confirmation tokens — single-use, TTL-bound proofs that an AI host actually
        ran calculate_price before place_order. Generated by the platform,
        verified by the platform.

    Idempotency  — dedupe on (scope, key) with body-hash safety check so a
        retry with the same key can't slip a different body through.

    Rate limit   — sliding window per (tenant_id, scope, user). Configured
        from tenant.yaml, raised as RateLimitExceeded.

    PII masking  — phone/email helpers used by formatters; raw values never
        leave the adapter response.

    Audit log    — ring buffer of every tool call (tenant, tool, user, success,
        duration). Surface to operators via /api/audit (M2).

    @audited_tool decorator — composes rate limit + audit + error capture in
        one wrapper that every MCP tool handler should be wearing.

The defaults are in-memory, single-process. M2 will swap a Redis backend in
behind the same interfaces without touching adapter or handler code.
"""

from __future__ import annotations

import functools
import hashlib
import json
import re
import secrets
import time
from collections import deque
from collections.abc import AsyncIterator, Awaitable, Callable
from contextlib import asynccontextmanager
from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import TYPE_CHECKING, Any

from brand_bridge.core.errors import (
    ConfirmationTokenError,
    IdempotencyError,
    RateLimitExceeded,
)

if TYPE_CHECKING:
    from brand_bridge.core.context import ToolContext

# ─── Confirmation tokens ──────────────────────────────────────────────────

_CONFIRMATION_TTL_SECONDS = 300
_TOKENS: dict[str, tuple[float, dict[str, Any]]] = {}


def generate_confirmation_token() -> str:
    """Mint a fresh single-use token. Call this from `calculate_price` and
    return it on the PriceQuote; the platform consumes it in `place_order`."""
    return f"cfm_{secrets.token_hex(8)}"


def register_confirmation_token(token: str, payload: dict[str, Any], *,
                                ttl: int = _CONFIRMATION_TTL_SECONDS) -> None:
    _TOKENS[token] = (time.time() + ttl, payload)


def consume_confirmation_token(token: str) -> dict[str, Any]:
    """Return the registered payload and delete the token. Raises if missing
    or expired. Tokens are single-use even on error — adapters that fail
    after consumption must not assume retry."""
    entry = _TOKENS.pop(token, None)
    if entry is None:
        raise ConfirmationTokenError("confirmation_token unknown or already used")
    expiry, payload = entry
    if time.time() > expiry:
        raise ConfirmationTokenError("confirmation_token expired")
    return payload


# ─── Idempotency store ────────────────────────────────────────────────────

@dataclass
class _IdemEntry:
    body_hash: str
    response: Any
    created_at: float


class IdempotencyStore:
    """In-memory, single-process. Replace with Redis in M2 by swapping the
    instance bound to DEFAULT_IDEMPOTENCY_STORE."""

    def __init__(self, ttl_seconds: int = 86_400) -> None:
        self._store: dict[tuple[str, str], _IdemEntry] = {}
        self._ttl = ttl_seconds

    @staticmethod
    def hash_body(payload: Any) -> str:
        normalized = json.dumps(payload, sort_keys=True, default=str)
        return hashlib.sha256(normalized.encode()).hexdigest()

    def lookup(self, scope: str, key: str, body_hash: str) -> Any | None:
        entry = self._store.get((scope, key))
        if entry is None:
            return None
        if time.time() - entry.created_at > self._ttl:
            self._store.pop((scope, key), None)
            return None
        if entry.body_hash != body_hash:
            raise IdempotencyError(
                f"idempotency key '{key}' reused with a different body — "
                "callers must use a fresh key for a different request",
            )
        return entry.response

    def store(self, scope: str, key: str, body_hash: str, response: Any) -> None:
        self._store[(scope, key)] = _IdemEntry(body_hash, response, time.time())


DEFAULT_IDEMPOTENCY_STORE = IdempotencyStore()


# ─── Rate limit (sliding window) ─────────────────────────────────────────

class RateLimiter:
    def __init__(self) -> None:
        self._buckets: dict[tuple[str, str, str], deque[float]] = {}

    def check(self, *, tenant_id: str, scope: str, key: str,
              max_calls: int, window_seconds: int) -> None:
        bucket_id = (tenant_id, scope, key)
        bucket = self._buckets.setdefault(bucket_id, deque())
        now = time.time()
        cutoff = now - window_seconds
        while bucket and bucket[0] < cutoff:
            bucket.popleft()
        if len(bucket) >= max_calls:
            raise RateLimitExceeded(
                f"rate limit exceeded: {scope} > {max_calls} calls / {window_seconds}s "
                f"(tenant={tenant_id}, key={key})",
            )
        bucket.append(now)


DEFAULT_RATE_LIMITER = RateLimiter()


# ─── PII masking ──────────────────────────────────────────────────────────

_PHONE_RE = re.compile(r"^\+?[\d\-\s]{6,}$")
_EMAIL_RE = re.compile(r"^([^@]+)@(.+)$")


def mask_phone(phone: str | None) -> str:
    """Reduce a phone number to first-3 + **** + last-4. Idempotent — if the
    value already looks masked (contains '*'), return as-is. Returns empty
    string for empty/None input."""
    if not phone:
        return ""
    if "*" in phone:
        return phone
    digits = re.sub(r"\D", "", phone)
    if len(digits) < 7:
        return phone
    return f"{digits[:3]}****{digits[-4:]}"


def mask_email(email: str | None) -> str:
    if not email:
        return ""
    match = _EMAIL_RE.match(email)
    if not match:
        return email
    local, domain = match.groups()
    if len(local) <= 1:
        return f"{local}***@{domain}"
    return f"{local[0]}***@{domain}"


# ─── Audit log ────────────────────────────────────────────────────────────

@dataclass
class AuditEntry:
    tool: str
    tenant_id: str
    user_id: str
    success: bool
    duration_ms: int
    timestamp: str
    error: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)


class AuditLog:
    def __init__(self, max_entries: int = 10_000) -> None:
        self._entries: deque[AuditEntry] = deque(maxlen=max_entries)

    def append(self, entry: AuditEntry) -> None:
        self._entries.append(entry)

    def tail(self, limit: int = 100) -> list[AuditEntry]:
        return list(self._entries)[-limit:]

    def clear(self) -> None:
        self._entries.clear()


DEFAULT_AUDIT_LOG = AuditLog()


# ─── @audited_tool decorator ─────────────────────────────────────────────

@asynccontextmanager
async def audited(ctx: ToolContext, *, name: str,
                  rate_class: str = "L1") -> AsyncIterator[ToolContext]:
    """Context-manager variant of `@audited_tool` for callers that build the
    ToolContext inline (e.g. MCP tool handlers exposed via FastMCP, where the
    user-facing signature can't carry `ctx` as the first arg).

    Usage::

        async with audited(ctx, name="list_stores", rate_class="L0"):
            return await ctx.registry.master_data.list_stores(...)
    """
    started = time.time()
    error = ""
    success = False
    try:
        rate_spec = ctx.config.rate_limits.get(rate_class)
        if rate_spec is not None:
            DEFAULT_RATE_LIMITER.check(
                tenant_id=ctx.tenant_id, scope=name, key=ctx.user_id,
                max_calls=rate_spec.max_calls,
                window_seconds=rate_spec.window_seconds,
            )
        yield ctx
        success = True
    except Exception as e:  # noqa: BLE001
        error = f"{type(e).__name__}: {e}"
        raise
    finally:
        DEFAULT_AUDIT_LOG.append(AuditEntry(
            tool=name, tenant_id=ctx.tenant_id, user_id=ctx.user_id,
            success=success,
            duration_ms=int((time.time() - started) * 1000),
            timestamp=datetime.now(UTC).isoformat(),
            error=error,
        ))


def audited_tool(*, name: str, rate_class: str = "L1"):
    """Wrap an async tool handler with rate limit + audit log + error capture.

    Handler signature: ``async def handler(ctx: ToolContext, **kwargs)``.
    The wrapper looks up the configured rate limit on ``ctx.config.rate_limits``
    by `rate_class`, applies it keyed on `ctx.user_id`, then invokes the handler.
    Audit entry is always written, even on error.
    """
    def decorator(fn: Callable[..., Awaitable[Any]]):
        @functools.wraps(fn)
        async def wrapper(ctx, **kwargs):
            started = time.time()
            error = ""
            success = False
            try:
                rate_spec = ctx.config.rate_limits.get(rate_class)
                if rate_spec is not None:
                    DEFAULT_RATE_LIMITER.check(
                        tenant_id=ctx.tenant_id, scope=name, key=ctx.user_id,
                        max_calls=rate_spec.max_calls,
                        window_seconds=rate_spec.window_seconds,
                    )
                result = await fn(ctx, **kwargs)
                success = True
                return result
            except Exception as e:  # noqa: BLE001
                error = f"{type(e).__name__}: {e}"
                raise
            finally:
                DEFAULT_AUDIT_LOG.append(AuditEntry(
                    tool=name, tenant_id=ctx.tenant_id, user_id=ctx.user_id,
                    success=success,
                    duration_ms=int((time.time() - started) * 1000),
                    timestamp=datetime.now(UTC).isoformat(),
                    error=error,
                ))
        return wrapper
    return decorator
